// Nombres en español para el contenido del SRD 5.2. Las descripciones largas se quedan en inglés (texto oficial del SRD).
module.exports = {
  abilities: {
    str: ['FUE', 'Fuerza'], dex: ['DES', 'Destreza'], con: ['CON', 'Constitución'],
    int: ['INT', 'Inteligencia'], wis: ['SAB', 'Sabiduría'], cha: ['CAR', 'Carisma'],
  },
  skills: {
    acrobatics: 'Acrobacias', 'animal-handling': 'Trato con animales', arcana: 'Arcanos', athletics: 'Atletismo',
    deception: 'Engaño', history: 'Historia', insight: 'Perspicacia', intimidation: 'Intimidación',
    investigation: 'Investigación', medicine: 'Medicina', nature: 'Naturaleza', perception: 'Percepción',
    performance: 'Interpretación', persuasion: 'Persuasión', religion: 'Religión', 'sleight-of-hand': 'Juego de manos',
    stealth: 'Sigilo', survival: 'Supervivencia',
  },
  classes: {
    barbarian: 'Bárbaro', bard: 'Bardo', cleric: 'Clérigo', druid: 'Druida', fighter: 'Guerrero', monk: 'Monje',
    paladin: 'Paladín', ranger: 'Explorador', rogue: 'Pícaro', sorcerer: 'Hechicero', warlock: 'Brujo', wizard: 'Mago',
  },
  species: {
    dragonborn: 'Dracónido', dwarf: 'Enano', elf: 'Elfo', gnome: 'Gnomo', goliath: 'Goliat', halfling: 'Mediano',
    human: 'Humano', orc: 'Orco', tiefling: 'Tiflin',
  },
  subspecies: {
    'draconic-ancestor-black': 'Ancestro dracónico: negro', 'draconic-ancestor-blue': 'Ancestro dracónico: azul',
    'draconic-ancestor-brass': 'Ancestro dracónico: latón', 'draconic-ancestor-bronze': 'Ancestro dracónico: bronce',
    'draconic-ancestor-copper': 'Ancestro dracónico: cobre', 'draconic-ancestor-gold': 'Ancestro dracónico: oro',
    'draconic-ancestor-green': 'Ancestro dracónico: verde', 'draconic-ancestor-red': 'Ancestro dracónico: rojo',
    'draconic-ancestor-silver': 'Ancestro dracónico: plata', 'draconic-ancestor-white': 'Ancestro dracónico: blanco',
    'elven-lineage-drow': 'Linaje élfico: drow', 'elven-lineage-high-elf': 'Linaje élfico: alto elfo',
    'elven-lineage-wood-elf': 'Linaje élfico: elfo silvano',
    'gnomish-lineage-forest-gnome': 'Linaje gnómico: gnomo de los bosques', 'gnomish-lineage-rock-gnome': 'Linaje gnómico: gnomo de las rocas',
    'giant-ancestry-clouds-jaunt': 'Ancestro gigante: salto de las nubes', 'giant-ancestry-fires-burn': 'Ancestro gigante: abrasión del fuego',
    'giant-ancestry-frosts-chill': 'Ancestro gigante: frío de la escarcha', 'giant-ancestry-hills-tumble': 'Ancestro gigante: derribo de la colina',
    'giant-ancestry-stones-endurance': 'Ancestro gigante: aguante de la piedra', 'giant-ancestry-storms-thunder': 'Ancestro gigante: trueno de la tormenta',
    'fiendish-legacy-abyssal': 'Legado infernal: abisal', 'fiendish-legacy-chthonic': 'Legado infernal: ctónico',
    'fiendish-legacy-infernal': 'Legado infernal: infernal',
  },
  backgrounds: { acolyte: 'Acólito', criminal: 'Criminal', sage: 'Sabio', soldier: 'Soldado' },
  feats: {
    alert: 'Alerta', 'magic-initiate': 'Iniciado en la magia', 'savage-attacker': 'Atacante salvaje', skilled: 'Habilidoso',
    'ability-score-improvement': 'Mejora de característica', grappler: 'Agarrador', archery: 'Tiro con arco',
    defense: 'Defensa', 'great-weapon-fighting': 'Lucha con armas grandes', 'two-weapon-fighting': 'Lucha con dos armas',
    'boon-of-combat-prowess': 'Don de la destreza en combate', 'boon-of-dimensional-travel': 'Don del viaje dimensional',
    'boon-of-fate': 'Don del destino', 'boon-of-irresistible-offense': 'Don de la ofensiva irresistible',
    'boon-of-spell-recall': 'Don de la recuperación de conjuros', 'boon-of-the-night-spirit': 'Don del espíritu nocturno',
    'boon-of-truesight': 'Don de la visión verdadera',
  },
  featTypes: { origin: 'De origen', general: 'General', 'fighting-style': 'Estilo de combate', 'epic-boon': 'Don épico' },
  schools: {
    abjuration: 'Abjuración', conjuration: 'Conjuración', divination: 'Adivinación', enchantment: 'Encantamiento',
    evocation: 'Evocación', illusion: 'Ilusión', necromancy: 'Nigromancia', transmutation: 'Transmutación',
  },
  damage: {
    acid: 'ácido', bludgeoning: 'contundente', cold: 'frío', fire: 'fuego', force: 'fuerza', lightning: 'relámpago',
    necrotic: 'necrótico', piercing: 'perforante', poison: 'veneno', psychic: 'psíquico', radiant: 'radiante',
    slashing: 'cortante', thunder: 'trueno',
  },
  conditions: {
    blinded: 'Cegado', charmed: 'Hechizado', deafened: 'Ensordecido', exhaustion: 'Agotamiento', frightened: 'Asustado',
    grappled: 'Agarrado', incapacitated: 'Incapacitado', invisible: 'Invisible', paralyzed: 'Paralizado',
    petrified: 'Petrificado', poisoned: 'Envenenado', prone: 'Derribado', restrained: 'Apresado', stunned: 'Aturdido',
    unconscious: 'Inconsciente',
  },
  properties: {
    ammunition: 'Munición', finesse: 'Sutil', heavy: 'Pesada', light: 'Ligera', loading: 'Recarga', range: 'Distancia',
    reach: 'Alcance', thrown: 'Arrojadiza', 'two-handed': 'A dos manos', versatile: 'Versátil',
  },
  mastery: { cleave: 'Hendir', graze: 'Rozar', nick: 'Mellar', push: 'Empujar', sap: 'Debilitar', slow: 'Ralentizar', topple: 'Derribar', vex: 'Hostigar' },
  weapons: {
    club: 'Garrote', dagger: 'Daga', greatclub: 'Gran garrote', handaxe: 'Hacha de mano', javelin: 'Jabalina',
    'light-hammer': 'Martillo ligero', mace: 'Maza', quarterstaff: 'Bastón', sickle: 'Hoz', spear: 'Lanza',
    dart: 'Dardo', 'light-crossbow': 'Ballesta ligera', shortbow: 'Arco corto', sling: 'Honda',
    battleaxe: 'Hacha de guerra', flail: 'Mangual', glaive: 'Guja', greataxe: 'Gran hacha', greatsword: 'Espadón',
    halberd: 'Alabarda', lance: 'Lanza de caballería', longsword: 'Espada larga', maul: 'Mazo de guerra',
    morningstar: 'Lucero del alba', pike: 'Pica', rapier: 'Estoque', scimitar: 'Cimitarra', shortsword: 'Espada corta',
    trident: 'Tridente', warhammer: 'Martillo de guerra', 'war-pick': 'Pico de guerra', whip: 'Látigo',
    blowgun: 'Cerbatana', 'hand-crossbow': 'Ballesta de mano', 'heavy-crossbow': 'Ballesta pesada', longbow: 'Arco largo',
    musket: 'Mosquete', pistol: 'Pistola',
  },
  armor: {
    'padded-armor': 'Armadura acolchada', 'leather-armor': 'Armadura de cuero', 'studded-leather-armor': 'Cuero tachonado',
    'hide-armor': 'Armadura de pieles', 'chain-shirt': 'Camisote de malla', 'scale-mail': 'Cota de escamas',
    breastplate: 'Coraza', 'half-plate-armor': 'Media armadura', 'ring-mail': 'Cota de anillas', 'chain-mail': 'Cota de malla',
    'splint-armor': 'Armadura de bandas', 'plate-armor': 'Armadura de placas', shield: 'Escudo',
  },
  alignments: {
    'lawful-good': 'Legal bueno', 'neutral-good': 'Neutral bueno', 'chaotic-good': 'Caótico bueno',
    'lawful-neutral': 'Legal neutral', neutral: 'Neutral', 'chaotic-neutral': 'Caótico neutral',
    'lawful-evil': 'Legal malvado', 'neutral-evil': 'Neutral malvado', 'chaotic-evil': 'Caótico malvado', unaligned: 'Sin alineamiento',
  },
  sizes: { 'Medium or Small': 'Mediano o Pequeño', Tiny: 'Diminuto', Small: 'Pequeño', Medium: 'Mediano', Large: 'Grande', Huge: 'Enorme', Gargantuan: 'Gargantuesco' },
  monsterTypes: {
    aberration: 'Aberración', beast: 'Bestia', celestial: 'Celestial', construct: 'Constructo', dragon: 'Dragón',
    elemental: 'Elemental', fey: 'Feérico', fiend: 'Infernal', giant: 'Gigante', humanoid: 'Humanoide',
    monstrosity: 'Monstruosidad', ooze: 'Cieno', plant: 'Planta', 'swarm of tiny beasts': 'Enjambre de bestias diminutas',
    'swarm of tiny undead': 'Enjambre de muertos vivientes diminutos', undead: 'Muerto viviente',
  },
  rarity: { Common: 'Común', Uncommon: 'Infrecuente', Rare: 'Raro', 'Very Rare': 'Muy raro', Legendary: 'Legendario', Artifact: 'Artefacto', Varies: 'Variable' },
  spells: {
    'acid-splash': 'Salpicadura ácida', 'chill-touch': 'Toque gélido', 'dancing-lights': 'Luces danzantes', druidcraft: 'Druidismo',
    'eldritch-blast': 'Descarga sobrenatural', 'fire-bolt': 'Descarga de fuego', guidance: 'Orientación', light: 'Luz',
    'mage-hand': 'Mano de mago', mending: 'Reparar', message: 'Mensaje', 'minor-illusion': 'Ilusión menor',
    'poison-spray': 'Rociada venenosa', prestidigitation: 'Prestidigitación', 'produce-flame': 'Producir llama',
    'ray-of-frost': 'Rayo de escarcha', resistance: 'Resistencia', 'sacred-flame': 'Llama sagrada', shillelagh: 'Shillelagh',
    'shocking-grasp': 'Agarre electrizante', 'spare-the-dying': 'Estabilizar', thaumaturgy: 'Taumaturgia',
    'true-strike': 'Golpe certero', 'vicious-mockery': 'Burla cruel', 'starry-wisp': 'Destello estelar',
    'sorcerous-burst': 'Estallido hechicero', elementalism: 'Elementalismo',
    alarm: 'Alarma', 'animal-friendship': 'Amistad con los animales', bane: 'Perdición', bless: 'Bendición',
    'burning-hands': 'Manos ardientes', 'charm-person': 'Hechizar persona', 'color-spray': 'Rociada de color',
    command: 'Orden imperiosa', 'comprehend-languages': 'Comprensión idiomática', 'create-or-destroy-water': 'Crear o destruir agua',
    'cure-wounds': 'Curar heridas', 'detect-evil-and-good': 'Detectar el bien y el mal', 'detect-magic': 'Detectar magia',
    'detect-poison-and-disease': 'Detectar venenos y enfermedades', 'disguise-self': 'Disfrazarse', 'divine-favor': 'Favor divino',
    'divine-smite': 'Castigo divino', 'dissonant-whispers': 'Susurros disonantes', 'entangle': 'Enmarañar',
    'expeditious-retreat': 'Retirada expeditiva', 'faerie-fire': 'Fuego feérico', 'false-life': 'Falsa vida',
    'feather-fall': 'Caída de pluma', 'find-familiar': 'Encontrar familiar', 'fog-cloud': 'Nube de oscurecimiento',
    goodberry: 'Bayas buenas', grease: 'Grasa', 'guiding-bolt': 'Saeta guía', 'healing-word': 'Palabra de curación',
    'hellish-rebuke': 'Reprensión infernal', heroism: 'Heroísmo', hex: 'Maleficio', 'hunters-mark': 'Marca del cazador',
    'ice-knife': 'Cuchillo de hielo', identify: 'Identificar', 'inflict-wounds': 'Infligir heridas', jump: 'Salto',
    longstrider: 'Zancada prodigiosa', 'mage-armor': 'Armadura de mago', 'magic-missile': 'Proyectil mágico',
    'protection-from-evil-and-good': 'Protección contra el bien y el mal', 'ray-of-sickness': 'Rayo nauseabundo',
    sanctuary: 'Santuario', shield: 'Escudo', 'shield-of-faith': 'Escudo de fe', 'silent-image': 'Imagen silenciosa',
    sleep: 'Dormir', 'speak-with-animals': 'Hablar con los animales', thunderwave: 'Ola atronadora',
    'chromatic-orb': 'Orbe cromático', 'searing-smite': 'Castigo abrasador', 'thunderous-smite': 'Castigo atronador',
    'acid-arrow': 'Flecha ácida', aid: 'Ayuda', 'arcane-lock': 'Cerradura arcana', blindness: 'Ceguera/sordera',
    'blindness-deafness': 'Ceguera/sordera', blur: 'Desenfocarse', darkness: 'Oscuridad', darkvision: 'Visión en la oscuridad',
    'enhance-ability': 'Potenciar característica', 'flaming-sphere': 'Esfera flamígera', 'hold-person': 'Inmovilizar persona',
    invisibility: 'Invisibilidad', knock: 'Apertura', 'lesser-restoration': 'Restablecimiento menor', levitate: 'Levitar',
    'magic-weapon': 'Arma mágica', 'mirror-image': 'Imagen múltiple', 'misty-step': 'Paso brumoso', moonbeam: 'Rayo de luna',
    'prayer-of-healing': 'Plegaria de curación', 'scorching-ray': 'Rayo abrasador', 'see-invisibility': 'Ver invisibilidad',
    shatter: 'Romper', silence: 'Silencio', 'spider-climb': 'Trepar cual arácnido', 'spiritual-weapon': 'Arma espiritual',
    suggestion: 'Sugestión', web: 'Telaraña', 'mind-spike': 'Puñal mental', 'shining-smite': 'Castigo resplandeciente',
    'animate-dead': 'Animar a los muertos', 'bestow-curse': 'Lanzar maldición', blink: 'Intermitencia', counterspell: 'Contraconjuro',
    daylight: 'Luz del día', 'dispel-magic': 'Disipar magia', fear: 'Miedo', fireball: 'Bola de fuego', fly: 'Volar',
    'gaseous-form': 'Forma gaseosa', haste: 'Acelerar', 'hypnotic-pattern': 'Patrón hipnótico', 'lightning-bolt': 'Relámpago',
    'mass-healing-word': 'Palabra de curación en masa', 'protection-from-energy': 'Protección contra la energía',
    'remove-curse': 'Levantar maldición', revivify: 'Revivir', 'sleet-storm': 'Tormenta de aguanieve', slow: 'Ralentizar',
    'speak-with-dead': 'Hablar con los muertos', 'spirit-guardians': 'Espíritus guardianes', 'vampiric-touch': 'Toque vampírico',
    'water-breathing': 'Respirar bajo el agua', 'call-lightning': 'Llamar al relámpago',
    banishment: 'Destierro', blight: 'Plaga', 'dimension-door': 'Puerta dimensional', 'greater-invisibility': 'Invisibilidad mayor',
    'ice-storm': 'Tormenta de hielo', polymorph: 'Polimorfar', 'stoneskin': 'Piel pétrea', 'wall-of-fire': 'Muro de fuego',
    'cone-of-cold': 'Cono de frío', 'flame-strike': 'Descarga flamígera', 'mass-cure-wounds': 'Curar heridas en masa',
    'raise-dead': 'Revivir a los muertos', teleportation: 'Teletransporte', wish: 'Deseo', 'power-word-kill': 'Palabra de poder: matar',
    'meteor-swarm': 'Lluvia de meteoritos', 'time-stop': 'Detener el tiempo',
  },
  monsters: {
    'goblin-minion': 'Esbirro goblin', 'goblin-warrior': 'Guerrero goblin', 'goblin-boss': 'Jefe goblin',
    'hobgoblin-warrior': 'Guerrero hobgoblin', 'hobgoblin-captain': 'Capitán hobgoblin',
    'bugbear-warrior': 'Guerrero osgo', 'bugbear-stalker': 'Acechador osgo',
    skeleton: 'Esqueleto', zombie: 'Zombi', 'ogre-zombie': 'Zombi ogro', ghoul: 'Necrófago', ghast: 'Ghast', wight: 'Tumulario',
    mummy: 'Momia', 'mummy-lord': 'Señor momia', specter: 'Espectro', wraith: 'Aparición', ghost: 'Fantasma', lich: 'Liche',
    shadow: 'Sombra', 'vampire-spawn': 'Engendro vampírico', 'minotaur-skeleton': 'Esqueleto de minotauro',
    'warhorse-skeleton': 'Esqueleto de caballo de guerra',
    wolf: 'Lobo', 'dire-wolf': 'Lobo terrible', 'giant-spider': 'Araña gigante', 'brown-bear': 'Oso pardo',
    'black-bear': 'Oso negro', 'giant-rat': 'Rata gigante', 'swarm-of-bats': 'Enjambre de murciélagos', boar: 'Jabalí',
    ogre: 'Ogro', troll: 'Trol', owlbear: 'Osolechuza', 'young-red-dragon': 'Dragón rojo joven',
    'young-green-dragon': 'Dragón verde joven', 'red-dragon-wyrmling': 'Cría de dragón rojo',
    bandit: 'Bandido', 'bandit-captain': 'Capitán bandido', cultist: 'Sectario', 'cultist-fanatic': 'Fanático sectario',
    mage: 'Mago', priest: 'Sacerdote', guard: 'Guardia', knight: 'Caballero', veteran: 'Veterano',
  },
};
